### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by Driesboy** [comment]
ok

**Comment by Creeperface01** [comment]
Why i can not merge it by myself?

**Comment by Driesboy** [comment]
i make you one ok?

**Comment by Driesboy** [comment]
we are a team that search for the best minigames for pocketmine

**Comment by Creeperface01** [comment]
Ok thx i can develop color match here

**Comment by Driesboy** [comment]
ok

**Pull request merged**
